### ISSUE TITLE
Add Sample For Dynamic Admission Controller with that uses a Custom Resource

### ISSUE THREAD

**Issue by csviri** [operator-framework/josdk-webhooks#95]

**Comment by sflandergan** [comment]
Not sure if this is the right way but this is how I got the REST endpoint working:

```kotlin
import com.fasterxml.jackson.databind.ObjectMapper
import io.fabric8.kubernetes.api.model.GenericKubernetesResource
import io.fabric8.kubernetes.api.model.Namespaced
import io.fabric8.kubernetes.api.model.admission.v1.AdmissionReview
import io.fabric8.kubernetes.client.CustomResource
import io.fabric8.kubernetes.model.annotation.Group
import io.fabric8.kubernetes.model.annotation.Kind
import io.fabric8.kubernetes.model.annotation.Version
import io.javaoperatorsdk.webhook.admission.AdmissionController
import io.javaoperatorsdk.webhook.admission.validation.Validator
import org.springframework.context.annotation.Bean
import org.springframework.stereotype.Component
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.ResponseBody
import org.springframework.web.bind.annotation.RestController


@Group("mygroup")
@Kind("Sample")
@Version("v1")
class SampleCustomResource: CustomResource<Sample, SampleStatus>(), Namespaced

data class Sample(val field: String)

data class SampleStatus(val field: String)


@RestController
class SampleCustomResourceWebhookEndpoint(private val admissionController: AdmissionController<GenericKubernetesResource>) {
    @PostMapping("/validate")
    @ResponseBody
    fun validate(@RequestBody admissionReview: AdmissionReview): AdmissionReview =
            admissionController.handle(admissionReview)

}

@Component
class SampleCustomResourceWebHookConfiguration {

    @Bean
    fun admissionController(objectMapper: ObjectMapper): AdmissionController<GenericKubernetesResource> {
        return AdmissionController<GenericKubernetesResource>(Validator { resource: GenericKubernetesResource, _ ->
            val sampleResource = objectMapper.convertValue(resource.additionalProperties, SampleCustomResource::class.java)
            // do your validation here
        })
    }
}
```

When I send this http request:
```json
{
    "request": {
        "name": "sample",
        "namespace": "default",
        "object": {
            "apiVersion": "centersight.deviceinsight.com/v1",
            "kind": "Sample",
            "spec": {
                "field": "hello"
            }
        },
        "operation": "CREATE"
    }
}
```

I get a proper response:
```json
{
    "apiVersion": "admission.k8s.io/v1",
    "kind": "AdmissionReview",
    "response": {
        "allowed": true
    }
}
```

If I don't go via the `GenericKubernetesResource` I get a `ClassCastException`:

```
java.lang.ClassCastException: class io.fabric8.kubernetes.api.model.GenericKubernetesResource cannot be cast to class com.deviceinsight.sample.SampleCustomResource (io.fabric8.kubernetes.api.model.GenericKubernetesResource and com.deviceinsight.sample.SampleCustomResource are in unnamed module of loader 'app')
```

Would be great if the framework could handle the conversion from GenericKubernetesResource to the CustomResource itself

**Comment by csviri** [comment]
@sflandergan AFAIk `GenericKubernetesResource` serves a different purpose, it is intended to represent any resource in a generic way in fabric8 client.
What you are probably searching for is `HasMetadata` instead.

**Comment by sflandergan** [comment]
@csviri not really.
With `HasMetadata` I wouldn't  be able to access the CustomResource's spec.
That is stored within the `additionalProperties` field.

`AdmissionReview.request.object` is serialized as `GenericKubernetesResource` internally by the `kubernetes-webhooks-framework`.

**Comment by csviri** [comment]
> AdmissionReview.request.object is serialized as GenericKubernetesResource internally by the kubernetes-webhooks-framework.

Just if it cannot serialize to a proper resource. Because your resources is not registered for serialization.

If you are dealing just with custom resource you can use `CustomResource` as base class to access spec

**Comment by csviri** [comment]
see: https://github.com/java-operator-sdk/kubernetes-webooks-framework/tree/main/docs#using-custom-resources-in-the-api

**Comment by sflandergan** [comment]
Thanks for the input @csviri 
Unfortunately that does not work for me `java.lang.ClassCastException: class com.deviceinsight.sample.SampleCustomResource cannot be cast to class com.deviceinsight.sample.SampleCustomResource`

Maybe this is related to https://github.com/fabric8io/kubernetes-client/issues/5034

**Comment by sflandergan** [comment]
Just found out this comes from `spring-boot-devtools`.
When I remove the dependency it works :).
Thanks a lot!

**Comment by 10000-ki** [comment]
> If I don't go via the GenericKubernetesResource I get a ClassCastException:

@csviri 

I've had the same problem

https://github.com/operator-framework/josdk-webhooks/blob/8d95baa086468d2630a802b60f77907b7429c49a/core/src/main/java/io/javaoperatorsdk/webhook/admission/AdmissionUtils.java#L28

to solve this problem

```java
  public static <T> T getTargetResource(AdmissionRequest admissionRequest,
      Operation operation) {
    return operation == Operation.DELETE ? (T)admissionRequest.getOldObject()
        : (T)admissionRequest.getObject();
  }
```

we need to cast it as generic type instead of casting it as `KubernetesResource` type here.

I solved the problem as above.
